name: Auto-release on PR merge

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Releaser"
          git config --global user.email "test@github.nil"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.8'

      - name: Install scriv
        run: python -m pip install scriv

      - name: Create release
        run: |
          new_version="$(git tag --merged HEAD --sort v:refname | perl -nle 'print "$1.$2.", $3+1 if /^(\d+)\.(\d+)\.(\d+)$/' | tail -n1)"
          echo "[INFO] New version: $new_version"
          scriv collect --add --version "$new_version"
          git commit -m '[skip ci] Update CHANGELOG'
          git tag "$new_version"
          git push
          git push --tags
          scriv github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# vim:set sts=2:
